# Generated by Django 3.0.7 on 2020-08-04 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='interests',
        ),
        migrations.AddField(
            model_name='teacher',
            name='interests',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='account.Subject'),
            preserve_default=False,
        ),
    ]
