# Generated by Django 3.0.7 on 2020-08-13 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20200809_2104'),
        ('courses', '0003_auto_20200811_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='account.Teacher'),
        ),
    ]
