# Generated by Django 3.0.7 on 2020-08-20 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20200820_2121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='modules',
            options={'ordering': ('created',)},
        ),
    ]
