# Generated by Django 3.0.7 on 2020-08-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20200820_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='content',
            field=models.TextField(),
        ),
    ]
